theme: jekyll-theme-minimal
title: Mankind's Checklist
description: Once this project is completed, we will be 100% set as an species.
logo: world-and-person-creative-logo-unique-symbol-vector-27527752.jpg
