theme: jekyll-theme-minimal
title: Mankind's Checklist
description: 

We’ve been blindly evolving as a species, having an endless list of conflicts throughout our history, but what for? why would we fight ourselves? where do we want to get to by having more advanced technology?

There might be lots of answers for these questions, but I have my own, we’ve been fighting for order, well-being and superiority amongst other countries and regions because that’s what we know. But once we leave Earth, such as we are by exploring and colonizing Mars and beyond, once we start operating in more planets, it is just pointless to keep being divided and competing against other nations on space. We need a common goal, we need to collaborate for the fastest advance possible. And this is assuming we are alone, if we find other species, we don’t just need to be united for resources, but for survival and organization in a “stellar” society.

This is where Mankind’s Checklist is created, a universal, yet simple table that gives us purpose as humans, that settles a common goal and drives us together, making conflicts, and even nations in a future, pointless.

You can consider this a religion, a project, whatever you’d like. This idea surges aiming to give every individual on earth and beyond a reason to live and a key to contribute to society, and to give governments and excuse to eventually bind together, making it so Earth is a country by itself in which everybody with no exception has a dignified life.

Once this project is completed, we will be 100% set as an species.
